[package]
name = "ruthenian"
version = "0.0.1"
edition = "2021"
description = "Ruthenian language utilities- Inflection and NLP"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gold-silver-copper/ruthenian"
[dependencies]
